name: Checkmarx Groups Onboard

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI

jobs:
  run-checkmarx-onboarder:
    runs-on: ubuntu-latest

    env:
      CX_TOKEN: ${{ secrets.CX_EU_TOKEN }}
      TENANT_NAME: ${{ vars.CX_TENANT_NAME }}
      TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL }}
      TENANT_URL: ${{ vars.CX_TENANT_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Checkmarx Group Onboarder script
        run: python3 checkmarx_groups_onboarder.py -filename=github-project-groups.csv
