name: Checkmarx Groups Assignment

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      filename:
        description: 'Path to the project file (e.g. app_config.json)'
        required: true
      mode:
        description: 'mode to run the script'
        required: true

jobs:
  run-checkmarx-group-assignment:
    runs-on: ubuntu-latest

    env:
      CX_TOKEN: ${{ secrets.CX_EU_TOKEN }}
      TENANT_NAME: ${{ vars.CX_TENANT_NAME }}
      TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL }}
      TENANT_URL: ${{ vars.CX_TENANT_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Checkmarx Group Assignment script by tags
        run: python3 checkmarx_group_assignment.py -filename=${{ github.event.inputs.filename }} -mode=${{ github.event.inputs.mode }}
