name: Checkmarx Groups Onboard

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
    inputs:
      filename:
        description: 'Path to the project file (e.g. app_config.json)'
        required: true

jobs:
  run-checkmarx-groups-onboarder:
    runs-on: ubuntu-latest

    env:
      CX_TOKEN: ${{ secrets.CX_TOKEN }}
      TENANT_NAME: ${{ vars.CX_TENANT_NAME_PROD }}
      TENANT_IAM_URL: ${{ vars.CX_TENANT_IAM_URL_PROD }}
      TENANT_URL: ${{ vars.CX_TENANT_URL_PROD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Checkmarx Group Onboarder script
        run: python3 checkmarx_groups_onboarder.py -filename=${{ github.event.inputs.filename }}
